# docker-compose.yml
version: '3.9'

services:
  elysia-app:
    build: .
    ports: ["3000:3000"]
    #NOTE: default volume config might be wrong
    volumes: ["./:/app"]
  redis:
    image: redis
    volumes: ["redis-db:/data"]

volumes:
  redis-db:
